"""
Django settings for tareeqy_tracker project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-zgqjmhs9m7sl+68(vqw4(-r*m598uvc*)!(n^lvt1)12^t597j"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

FENCE_NAMES = [
    "صره","دير شرف", "عين سينيا", "روابي", "جبع","شافي شمرون","المربعه", "كفر عقب","جبارة","بيت فوريك",
    "عش الغراب", "راس الجوره","بوابة بورين","عورتا", "بزاريا", "دوار مخماس","بيت ايل","عيون الحرامية", 
    "الحمرا", "العيزرية", "عناتا","الكونتينر","يتسهار","زعترة", "الفندق","النبي يونس", "الفحص", "العجوري",
    "حومش", "عناب", "السدر", "المنشية", "حلحول","بيت كاحل", "سلفيت", "ترمسعيا", "العبيدية", "تقوع",
 "قلنديا", "حزما", "الزعيم", "قبر حلوة", "النشاش", "بيت جالا", "النفق", "جناتا", "الحضر", "راس الجورة",
  "فرش الهوا", "بني نعيم", "اذنا", "الظاهرية", "كرمة", "العروب" , "عبدة", "عين سينا", "زعترا"
  , "حواره", "البادان", "بني فاضل", "النبي صالح", "بيت ليد", "اريحا", "تياسير", "البانا", "كفر لاقف"
  , "عزون", "جيوس", "النبي الياس", "اماتين", "ياسوف", "كفل حارس", "حارس", "كانا", "بديا"
  , "استيا", "جماعين", "عقربا", "نور شمس" , "العيزريه"

]

# List of keywords for status
STATUS_KEYWORDS = {
    "open": ["مفتوح", "مفتوحة", "سالك", "سالكة","نظيف","فتحت","سالكه","فاتحات"],
    "closed": ["مغلق", "مغلقة", "ازمة", "مازم", "كثافة سير","ازمه"],
    "Minor_traffic_jam":[ ],
    "sever_traffic_jam":[],
}
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tareeqy"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tareeqy_tracker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tareeqy_tracker.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tareeqy_db',  # Your database name
        'USER': 'root',  # Using root user
        'PASSWORD': 'omaima2003',  # Your MySQL root password
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
