# Generated by Django 5.1.7 on 2025-06-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(unique=True)),
                ('text', models.TextField()),
                ('message_time', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(max_length=64)),
                ('is_modified', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FenceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('sever_traffic_jam', 'Severe Traffic Jam')], max_length=50)),
                ('message_time', models.DateTimeField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('fence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='tareeqy.fence')),
            ],
            options={
                'ordering': ['-message_time'],
                'unique_together': {('fence', 'message_time')},
            },
        ),
    ]
