# Generated by Django 5.1.7 on 2025-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareeqy", "0002_fence_delete_welcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="fence",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
