# Generated by Django 5.1.7 on 2025-03-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareeqy", "0003_fence_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fence",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="fence",
            name="message_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
