# Generated by Django 5.1.7 on 2025-03-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareeqy', '0004_remove_fence_timestamp_fence_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fence',
            name='message_time',
        ),
        migrations.RemoveField(
            model_name='fence',
            name='status',
        ),
        migrations.AddField(
            model_name='fence',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fence',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='FenceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('fence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='tareeqy.fence')),
            ],
        ),
    ]
