# Generated by Django 5.1.7 on 2025-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareeqy", "0005_remove_fence_message_time_remove_fence_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fencestatus",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
