# Generated by Django 5.1.7 on 2025-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareeqy", "0006_fencestatus_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fence",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="fencestatus",
            name="message_time",
            field=models.DateTimeField(),
        ),
    ]
